# Generated by Django 3.1.3 on 2020-12-28 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gadgets', '0002_auto_20201226_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfd',
            name='impf',
            field=models.ImageField(default='profile.jpg', upload_to='Profile/'),
        ),
        migrations.CreateModel(
            name='Mystore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilename', models.TextField()),
                ('mobilecompany', models.TextField()),
                ('ram', models.TextField()),
                ('rom', models.TextField()),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
