# Generated by Django 3.1.3 on 2020-12-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0003_auto_20201228_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='m',
        ),
    ]
