# Generated by Django 3.1.3 on 2020-12-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0004_remove_mystore_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mystore',
        ),
    ]
