# Generated by Django 3.1.3 on 2021-01-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0005_delete_mystore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Corrans', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'onlineexam',
            },
        ),
    ]
